# Generated by Django 5.0.6 on 2024-06-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('secondName', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
